---
name: Create packages and test installation

on:
  pull_request:

jobs:
  # Use a matrix for AlmaLinux versions
  build-almalinux:
    strategy:
      matrix:
        almalinux-version: [8, 9]
    name: Build AlmaLinux ${{ matrix.almalinux-version }} RPMs
    runs-on: ubuntu-latest
    container: almalinux:${{ matrix.almalinux-version }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          yum install -y rpm-build yum-utils rpmlint
          yum-builddep -y glite-info-provider-ldap.spec
      - name: build rpm
        run: |
          make clean rpm
          rpmlint --file .rpmlint.ini build/RPMS/noarch/*.el${{ matrix.almalinux-version }}.noarch.rpm
      - name: Upload RPMs
        uses: actions/upload-artifact@v3
        with:
          name: rpms${{ matrix.almalinux-version }}
          path: |
            build/RPMS/noarch/glite-info-provider-ldap-*.el${{ matrix.almalinux-version }}.noarch.rpm

  # XXX: From PowerTools: openldap-servers
  install-almalinux8:
    name: Install AlmaLinux 8 RPMs
    needs: build-almalinux
    runs-on: ubuntu-latest
    container: almalinux:8
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: rpms8
      - name: Install generated RPMs
        run: |
          yum install -y dnf-plugins-core
          dnf config-manager --set-enabled powertools
          yum localinstall -y glite-info-provider-ldap-*.el8.noarch.rpm
      - name: Call script, check usage is shown
        run: |
          /usr/libexec/glite-info-provider-ldap -h 2>&1 | grep -q '^Usage: /usr/libexec/glite-info-provider-ldap'

  # XXX Dependencies from EPEL: openldap-servers
  install-almalinux9:
    name: Install AlmaLinux 9 RPMs
    needs: build-almalinux
    runs-on: ubuntu-latest
    container: almalinux:9
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: rpms9
      - name: Install generated RPMs
        run: |
          yum install -y epel-release
          yum localinstall -y glite-info-provider-ldap-*.el9.noarch.rpm
      - name: Call script, check usage is shown
        run: |
          /usr/libexec/glite-info-provider-ldap -h 2>&1 | grep -q '^Usage: /usr/libexec/glite-info-provider-ldap'
